package org.pingclubmanager.domain.model.application;
// Generated 23 mars 2018 16:07:51 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.inspiresoftware.lib.dto.geda.annotations.Dto;
import com.inspiresoftware.lib.dto.geda.annotations.DtoField;

/**
 * Player generated by hbm2java
 */
@Entity
@Table(name = "player")
@Dto
public class Player implements java.io.Serializable {

	private static final long serialVersionUID = -738189634439514678L;
	@DtoField
	private Integer id;
	@DtoField
	private String name;
	@DtoField
	private String firstname;
	@DtoField
	private String licence;
	@DtoField
	private Integer points;
	@DtoField
	private Boolean isTransferred;

	public Player() {
	}

	public Player(Integer id) {
		this.id = id;
	}

	public Player(Integer id, String name, String firstname, String licence, Integer points, Boolean isTransferred) {
		this.id = id;
		this.name = name;
		this.firstname = firstname;
		this.licence = licence;
		this.points = points;
		this.isTransferred = isTransferred;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.AUTO)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "firstname")
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "licence")
	public String getLicence() {
		return this.licence;
	}

	public void setLicence(String licence) {
		this.licence = licence;
	}

	@Column(name = "points")
	public Integer getPoints() {
		return this.points;
	}

	public void setPoints(Integer points) {
		this.points = points;
	}

	@Column(name = "is_transferred")
	public Boolean getIsTransferred() {
		return this.isTransferred;
	}

	public void setIsTransferred(Boolean isTransferred) {
		this.isTransferred = isTransferred;
	}

}
